### ISSUE TITLE
Can't set rules: key error window_class

### ISSUE THREAD

**Issue by indeedwatson** [fennerm/flashfocus#43] opened 2020-02-08 01:53 UTC
```python
 > ~ INFO: Detected display protocol: X11                                                            ⚙ 1
INFO: Loading configuration from /home/yama/.config/flashfocus/flashfocus.yml
INFO: Initializing with parameters:
{'ntimepoints': 10, 'default_opacity': 1.0, 'rules': [{'window_class': re.compile('Termite'), 'default_opacity': 0.8, 'flash_opacity': 0.6, 'simple': False, 'flash_on_focus': True, 'ntimepoints': 10, 'time': 600.0, 'flash_lone_windows': 'always'}], 'flash_on_focus': True, 'flash_opacity': 0.6, 'time': 600.0, 'simple': False, 'flash_fullscreen': True, 'flash_lone_windows': 'always'}
INFO: Initializing default window opacity...
INFO: Setting all windows to their default opacity...
Traceback (most recent call last):
  File "/usr/bin/flashfocus", line 12, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/flashfocus/cli.py", line 87, in cli
    init_server(kwargs)
  File "/usr/lib/python3.8/site-packages/flashfocus/cli.py", line 106, in init_server
    return server.event_loop()
  File "/usr/lib/python3.8/site-packages/flashfocus/server.py", line 55, in event_loop
    self._set_all_window_opacity_to_default()
  File "/usr/lib/python3.8/site-packages/flashfocus/server.py", line 105, in _set_all_window_opacity_to_default
    self.router.route_request(WMEvent(window=window, event_type=WMEventType.WINDOW_INIT))
  File "/usr/lib/python3.8/site-packages/flashfocus/router.py", line 102, in route_request
    self._route_window_init(message.window)
  File "/usr/lib/python3.8/site-packages/flashfocus/router.py", line 117, in _route_window_init
    rule, flasher = self._match(window)
  File "/usr/lib/python3.8/site-packages/flashfocus/router.py", line 140, in _match
    if window.match(rule):
  File "/usr/lib/python3.8/site-packages/flashfocus/display_protocols/x11.py", line 113, in match
    if criteria.get(prop) and not match_regex(criteria[prop], self.properties[prop]):
KeyError: 'window_class'
```

Only getting this error when I uncomment:

```yml
rules:
  - window-class: Termite
  default-opacity: 0.8
```

**Comment by fennerm** [comment] 2020-02-08 19:40
Based on that snippet I’d guess you have an indentation issue. default-opacity should have same indentation level as window-class

**Comment by indeedwatson** [comment] 2020-02-08 20:14
This how it should be?

```yml
rules:
  - window-class: Termite
    default-opacity: 0.8
```

Cause that gives me the same error.

**Comment by fennerm** [comment] 2020-02-08 21:00
Gotcha sounds like thats not it then. I’ll look into it

**Comment by Leo-Lahti** [comment] 2020-02-10 03:53
Same on sway
``` rules:
   - app-id: floating-term
     flash-on-focus: False
```
```❯ flashfocus
INFO: Detected display protocol: wayland - sway
Traceback (most recent call last):
  File "/usr/bin/flashfocus", line 12, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/flashfocus/cli.py", line 87, in cli
    init_server(kwargs)
  File "/usr/lib/python3.8/site-packages/flashfocus/cli.py", line 101, in init_server
    config = load_merged_config(config_file_path=Path(config_file_path), cli_options=cli_options)
  File "/usr/lib/python3.8/site-packages/flashfocus/config.py", line 324, in load_merged_config
    user_config = load_config(config_file_path)
  File "/usr/lib/python3.8/site-packages/flashfocus/config.py", line 146, in load_config
    config: Dict = yaml.load(f, Loader=yaml.FullLoader)
  File "/usr/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3.8/site-packages/yaml/constructor.py", line 41, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3.8/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "/home/hm7/.config/flashfocus/flashfocus.yml", line 6, column 1
expected <block end>, but found '<block mapping start>'
  in "/home/hm7/.config/flashfocus/flashfocus.yml", line 86, column 2```

**Comment by Leo-Lahti** [comment] 2020-02-18 21:36
``` rules:
   - app-id: floating-term
     flash-on-focus: False
```
Gives

```❯ flashfocus
INFO: Detected display protocol: wayland - sway
Traceback (most recent call last):
  File "/usr/bin/flashfocus", line 12, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/flashfocus/cli.py", line 87, in cli
    init_server(kwargs)
  File "/usr/lib/python3.8/site-packages/flashfocus/cli.py", line 101, in init_server
    config = load_merged_config(config_file_path=Path(config_file_path), cli_options=cli_options)
  File "/usr/lib/python3.8/site-packages/flashfocus/config.py", line 324, in load_merged_config
    user_config = load_config(config_file_path)
  File "/usr/lib/python3.8/site-packages/flashfocus/config.py", line 146, in load_config
    config: Dict = yaml.load(f, Loader=yaml.FullLoader)
  File "/usr/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3.8/site-packages/yaml/constructor.py", line 41, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3.8/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],```

**Comment by fennerm** [comment] 2020-02-20 16:21
Ugh sorry I haven’t had time to look into this yet

**Comment by fennerm** [comment] 2020-03-01 23:00
@indeedwatson @Leo-Lahti I'm not able to replicate either of these on my machine. Could you paste the output of `pip freeze`?

**Comment by indeedwatson** [comment] 2020-03-01 23:23
@fennerm https://paste.xinu.at/rGyXo/

**Comment by fennerm** [comment] 2020-03-08 21:12
@indeedwatson I still haven't been able to reproduce but I have a hunch that there is a window weirdly defined window id/class that is throwing things off. I pushed a release (v2.1.2) which better handles windows with absent class. Let me know if this improves things. 

@Leo-Lahti I think your issue is probably unrelated. Could you post the output of `pip freeze` and the contents of your config file?

**Comment by indeedwatson** [comment] 2020-03-10 19:56
@fennerm Yup looks like that solved it. Feel free to close if you deem leo's issue to be a separate one.

**Comment by Leo-Lahti** [comment] 2020-03-13 22:21
@fennerm 
hmmm seems like it works after i removed spaces from the front of rules: and indented app-id and flash-on-focus correctly

doesnt work
```
 rules:
   - app-id: floating-term
     flash-on-focus: False
```
works
```
rules:
  - app-id: floating-term
    flash-on-focus: False
```

**Comment by fennerm** [comment] 2020-03-14 23:03
Ah I see, yeah yaml is a stickler for spacing. I'll close this out. Looks like this error also wasn't being caught correctly. Fixing that in another patch release.

**Closed by fennerm** 2020-03-14 23:03 UTC
