### ISSUE TITLE
[Request] Change flash color

### ISSUE THREAD

**Issue by Cyberdr3am** [fennerm/flashfocus#53] opened 2020-06-17 07:06 UTC
Hi,

Thx for your work i love it.
Can you add the possibility to change the color during the flash.

So it will be possible with the configuration file to choose through a color code the color of the flash that you want.

Thx

**Comment by fennerm** [comment] 2020-06-30 15:23
@Cyberdr3am Closing this as a duplicate of https://github.com/fennerm/flashfocus/issues/1. Very much on board with this suggestion but it would require some major changes to the way flashfocus works

**Closed by fennerm** 2020-06-30 15:23 UTC
